# Generated by Django 4.0.4 on 2022-05-19 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=40)),
                ('Address', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=40)),
                ('Position', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=40)),
                ('Resume', models.FileField(blank=True, upload_to='static/resume/')),
                ('Applied_for', models.CharField(max_length=40)),
                ('Applied_on', models.DateTimeField(default=datetime.datetime(2022, 5, 19, 9, 53, 5, 539825))),
                ('Status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ON ASSIGNMENT', 'On Hold')], default='ON ASSIGNMENT', max_length=15)),
                ('Skills', models.TextField(default='relax')),
            ],
        ),
    ]
