# Generated by Django 4.0.4 on 2022-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Skills',
            field=models.TextField(default='Skill Here', unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Status',
            field=models.CharField(choices=[('Acc', 'Accepted'), ('Rej', 'Rejected'), ('Hold', 'On Hold')], default='Hold', max_length=10),
        ),
    ]
