# Generated by Django 4.0.4 on 2022-05-19 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Applied_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 10, 1, 43, 745640)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
